name: Pylint

on: 
  pull_request:
    branches: [ staging ]
  
  # Allows the job to be run From GitHub   
  workflow_dispatch:

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint `ls CppStlPython/ | grep "[A-Za-z][A-Za-z\_].py"`
