name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow or pull request events in staging
  push:
    branches:
      - staging
  pull_request:
    branches: 
      - staging

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Sets up py env       
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        
      - name: Run Tests
        run: python3 -m unittest tests/test*
